on:
  [workflow_dispatch]
  # schedule:
  #   - cron: "*/5 * * * *"

jobs:
  example-job:
    runs-on: ubuntu-latest
    name: Run a script in 2 steps
    steps:
      - name: show pwd
        run: pwd
      - name: run internal
        run: node ../.github/scripts/scheduler.js
      # - name: run script
      #   run: node "/home/resources/scheduler.js"
