on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  # get_adventure_pass_owners:
  #   runs-on: ubuntu-latest
  #   name: get passes
  #   steps:
  #     - name: fetch data
  #       id: hello
  #       uses: OGStefs/tigers@master
  #       with:
  #         who-to-greet: "Mona the Octocat"
  #     # Use the output from the `hello` step
  #     - name: Get the output time

  example-job:
    runs-on: ubuntu-latest
    name: Connect to PostgreSQL
    steps:
      - name: run script
        run: node "../../resources/scheduler.js"
