on:
  [workflow_dispatch]
  # schedule:
  #   - cron: "*/5 * * * *"

jobs:
  get_adventure_pass:
    runs-on: ubuntu-latest
    # name: Get all the adventure Pass owners
    steps:
      - name: Some stupid unrelated name
        env:
          MORALIS: ${{ secrets.MORALIS }}
        uses: OGStefs/tigers@master
      - name: commit file
        run: |
          pwd
          cd tigers
          git config --global user.email "stefanistweg@gmail.com"
          git config --global user.name "OGStefs"
          git add .
          git commit -m "Update json"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
