on:
  [workflow_dispatch]
  # schedule:
  #   - cron: "*/5 * * * *"

jobs:
  get_adventure_pass:
    runs-on: ubuntu-latest
    # name: Get all the adventure Pass owners
    steps:
      - name: Some stupid unrelated name
        env:
          MORALIS: ${{ secrets.MORALIS }}
        uses: OGStefs/tigers@master
